
import { WorkshopData, Slide, SlideType } from './types';

export const AI_SDLC_SLIDES: Slide[] = [
  {
    number: 1,
    title: "The AI-Enhanced SDLC",
    type: "Title",
    visualDescription: "A circular infinity loop representing the SDLC, with glowing AI nodes highlighting every phase.",
    bullets: ["Supercharging the Lifecycle", "From Requirements to Maintenance", "Efficiency, Quality, & Speed", "The 2026 Engineering Standard"],
    speakerNotes: "AI doesn't replace the SDLC; it supercharges it. Every phase we know—planning, coding, testing—is now 10x faster and higher quality when integrated with the right AI workflows."
  },
  {
    number: 2,
    title: "Phase 1: Requirements & Planning",
    type: "Diagram",
    visualDescription: "Flow showing raw business ideas being transformed into structured PRDs and User Stories by an AI agent.",
    bullets: ["Auto-generate PRDs from notes", "AI-driven User Story mapping", "Edge case identification early on", "Effort estimation & Task breakdown"],
    speakerNotes: "We start at the beginning. AI can take messy stakeholder notes and turn them into professional Product Requirement Documents. It finds the edge cases you'd normally miss until production."
  },
  {
    number: 3,
    title: "Phase 2: Design & Architecture",
    type: "Content",
    visualDescription: "Icons for database schemas, API contracts, and Mermaid.js diagrams being generated by AI.",
    bullets: ["System architecture brainstorming", "AI-generated database schemas", "Auto-generating API contracts (OpenAPI)", "Mermaid.js diagram generation"],
    speakerNotes: "In the design phase, AI is your brainstorming partner. It can suggest database schemas based on your PRD and even draw the sequence diagrams for you using Mermaid.js code."
  },
  {
    number: 4,
    title: "Phase 3: Development",
    type: "Demo",
    visualDescription: "Split screen showing a developer using Cursor to generate a complex feature from a single architectural prompt.",
    bullets: ["AI-native IDE workflows (Cursor)", "Code generation from specs", "Automated refactoring & cleanup", "Context-aware logic suggestions"],
    speakerNotes: "Implementation is where we see the biggest speed boost. With AI-native IDEs like Cursor, we aren't just writing lines; we're orchestrating the implementation of entire features at once."
  },
  {
    number: 5,
    title: "Phase 4: Testing",
    type: "Exercise",
    visualDescription: "A testing pyramid with the 'Unit' and 'Integration' layers highlighted with AI icons.",
    bullets: ["Instant Unit Test generation", "AI-identified edge case scenarios", "Property-based testing with AI", "Auto-generated test data"],
    speakerNotes: "Testing is no longer a chore. AI can generate comprehensive unit and integration tests based on your logic, ensuring that edge cases are covered before you even run the code."
  },
  {
    number: 6,
    title: "Phase 5: Code Review & QA",
    type: "Diagram",
    visualDescription: "An AI 'Review Agent' flagging security vulnerabilities and naming convention issues in a PR.",
    bullets: ["AI as the first-pass reviewer", "Automated security scanning", "Consistency & Standards check", "Human-in-the-loop final audit"],
    speakerNotes: "Before a human even looks at a PR, an AI agent can perform a first-pass review. It checks for security vulnerabilities, naming conventions, and logical flaws, saving the senior dev's time."
  },
  {
    number: 7,
    title: "Phase 6: Deployment & Maintenance",
    type: "Content",
    visualDescription: "A dashboard showing AI-generated CI/CD scripts and a monitoring agent flagging a production anomaly.",
    bullets: ["AI-generated CI/CD pipelines", "Automated monitoring & alerting", "Incident response & Debugging", "Legacy code documentation"],
    speakerNotes: "Even deployment is automated. AI can draft your GitHub Actions or Jenkins scripts. In maintenance, AI monitors logs to identify and even suggest fixes for production incidents."
  },
  {
    number: 8,
    title: "Traditional vs. AI-SDLC",
    type: "Comparison",
    visualDescription: "A timeline comparison showing the 'Manual' SDLC taking weeks vs 'AI-Enhanced' taking days.",
    bullets: ["Trad: High boilerplate effort", "AI: Intent-based acceleration", "Trad: Late defect detection", "AI: Early validation & review"],
    speakerNotes: "The contrast is stark. Traditional SDLC is weighted down by manual boilerplate. AI-SDLC is intent-based, moving the effort from typing to architecting and reviewing."
  },
  {
    number: 9,
    title: "The Human Role in AI-SDLC",
    type: "Recap",
    visualDescription: "A developer standing at the center of the lifecycle, acting as the 'Conductor'.",
    bullets: ["Defining the Intent (Context)", "Architectural Decision Making", "Critical Quality Verification", "Security & Ethics Oversight"],
    speakerNotes: "Remember: AI doesn't run the show. You do. You are the architect defining the intent and the final judge of quality. AI handles the construction; you handle the engineering."
  },
  {
    number: 10,
    title: "Summary: Start Integrating",
    type: "Title",
    visualDescription: "A checklist of the next steps to move your team toward an AI-SDLC.",
    bullets: ["Pick one phase to automate today", "Establish AI review standards", "Focus on context preservation", "Build your AI toolset"],
    speakerNotes: "Don't try to change everything at once. Pick one phase—maybe testing or documentation—and start there. Build the habit of being an AI-native engineer."
  }
];

export const VIBE_ENGINEERING_SLIDES: Slide[] = [
  {
    number: 1,
    title: "Vibe Engineering: Beyond Vibe Coding",
    type: "Title",
    visualDescription: "Disciplined engineering blueprints meeting fluid AI neural networks. High-tech, professional aesthetic.",
    bullets: ["The Professional Methodology", "Ownership of Outcomes", "Engineering Rigor + AI Speed", "Architecting Systems, Not Snippets"],
    speakerNotes: "Welcome to Vibe Engineering. This is where we stop just 'vibing' and start 'engineering' with AI. It's the difference between a hack and a high-scale production system."
  },
  {
    number: 2,
    title: "Distinction: Coding vs. Engineering",
    type: "Comparison",
    visualDescription: "Vibe Coding (Ad-hoc, Fragile) vs. Vibe Engineering (Structured, Robust).",
    bullets: ["Coding: Prompt -> Generate -> Copy-Paste", "Engineering: Requirements -> Arch -> Assist -> Audit", "Coding: 'It runs' | Engineering: 'It scales'", "The shift from Assistant to Conductor"],
    speakerNotes: "Vibe coding is what hobbyists do; it's room-by-room construction without a plan. Vibe engineering is the professional standard—you own the architecture, the quality, and the risks."
  },
  {
    number: 3,
    title: "The 5 Pillars of Vibe Engineering",
    type: "Diagram",
    visualDescription: "Five pillars supporting a roof labeled 'Software Quality'.",
    bullets: ["1. Context: Feed AI structured intent", "2. Leadership: Human lead, AI accelerate", "3. Rigor: Same quality gates for all code", "4. Automation: AI-driven QA & Docs", "5. Responsibility: You own the outcome"],
    speakerNotes: "To master this, you must follow these five pillars. Context is your fuel, but Responsibility is your foundation. You are the one answerable for the bugs, even if AI suggested the code."
  },
  {
    number: 4,
    title: "The CLEAR Prompting Framework",
    type: "Content",
    visualDescription: "C-L-E-A-R vertical acronym breakdown with vibrant icons.",
    bullets: ["C: Context (Background & Constraints)", "L: Limitations (Security & Perf targets)", "E: Expectations (Output format & Standards)", "A: Architecture (Interfaces & Dependencies)", "R: Review Criteria (What 'good' looks like)"],
    speakerNotes: "Stop sending one-line prompts. Use the CLEAR framework to ensure the AI understands the architectural constraints and your quality expectations before it starts writing."
  },
  {
    number: 5,
    title: "Requirements & Architecture",
    type: "Diagram",
    visualDescription: "A brainstorming session between a human and an AI agent, generating ADRs.",
    bullets: ["AI-assisted stakeholder analysis", "Generating User Stories with validation", "Evaluating architectural patterns", "Creating AI-supported ADRs", "Architecture: Intentional, not emergent"],
    speakerNotes: "Don't let the AI decide your architecture by accident. Use it to explore options, generate sequence diagrams, and draft ADRs, but YOU make the final call on the system design."
  },
  {
    number: 6,
    title: "The 4-Pass Implementation Workflow",
    type: "Timeline",
    visualDescription: "A circular flow: Generate -> Review -> Test -> Refine.",
    bullets: ["1. GENERATE: Implementation with full context", "2. REVIEW: Deep logic & security audit", "3. TEST: Meaningful AI-generated assertions", "4. REFINE: Targeted feedback for polish"],
    speakerNotes: "This is our production loop. We never just 'copy-paste'. Every AI output passes through a human review, automated tests, and targeted refinement passes."
  },
  {
    number: 7,
    title: "AI-Powered Quality Assurance",
    type: "Diagram",
    visualDescription: "A testing pyramid being built by robotic arms and human supervisors.",
    bullets: ["Unit tests with meaningful assertions", "AI for edge case identification", "Security scanning (OWASP Top 10)", "Meta-Review: AI reviewing AI code"],
    speakerNotes: "Quality isn't hope. It's verification. We use AI to identify edge cases we might miss and run security scans on every generated module."
  },
  {
    number: 8,
    title: "Documentation & Knowledge",
    type: "Content",
    visualDescription: "Living documents that auto-update as code changes.",
    bullets: ["Living API documentation (OpenAPI)", "AI-assisted README maintenance", "Onboarding guides generated from logic", "Knowledge Base creation for teams"],
    speakerNotes: "Documentation is no longer an afterthought. Vibe engineering means the documentation is as code-integrated and alive as the system itself."
  },
  {
    number: 9,
    title: "Team Workflows & Scaling",
    type: "Diagram",
    visualDescription: "Multiple developers sharing a prompt library and standards.",
    bullets: ["Shared prompt libraries & templates", "Project-specific Custom Instructions", "AI Usage Guidelines & Policies", "Measuring real productivity, not LOC"],
    speakerNotes: "Scaling this to a team requires shared standards. We create project-wide 'system prompts' so the AI maintains consistency across the entire squad's output."
  },
  {
    number: 10,
    title: "The AI Maturity Model",
    type: "Comparison",
    visualDescription: "Level 0 (Manual) -> Level 1 (Vibe Coding) -> Level 2 (Vibe Coding+) -> Level 3 (Vibe Engineering).",
    bullets: ["Level 1: Fast but fragile", "Level 2: Faster with some review", "Level 3: Full engineering lifecycle", "Target: Green - Speed + Security + Scale"],
    speakerNotes: "Where are you on the maturity scale? Most are stuck at Level 1—fast but dangerous. We are aiming for Level 3: the fastest delivery with the highest reliability."
  },
  {
    number: 11,
    title: "Career Value: The Engineering Leader",
    type: "Recap",
    visualDescription: "A developer standing at the helm of a digital workforce.",
    bullets: ["Vibe Coder: Replaceable prompter", "Vibe Engineer: Irreplaceable leader", "Value isn't in 'typing lines'", "Value is in 'making decisions'"],
    speakerNotes: "Coding is becoming a commodity. Engineering is becoming more valuable than ever. Be the editor-in-chief, not just the writer."
  },
  {
    number: 12,
    title: "THE FUTURE IS ENGINEERED.",
    type: "Title",
    visualDescription: "Bold, clean text: 'VIBE ENGINEERING'.",
    bullets: ["AI writes code. Engineers build systems.", "Own your outcome.", "Master the intent.", "START ENGINEERING."],
    speakerNotes: "Vibe coding is asking AI to write your essay. Vibe engineering is being the editor-in-chief who uses AI to run a world-class newsroom. Let's build something real."
  }
];

export const LLM_AGENTIC_AI_SLIDES: Slide[] = [
  {
    number: 1,
    title: "LLM & Agentic AI",
    type: "Title",
    visualDescription: "Futuristic brain visualization with glowing pathways connecting various tech nodes.",
    bullets: ["Foundational Models to Agents", "The Era of Autonomous Coding", "Understanding Reasoning Models", "Mastering Agentic Workflows"],
    speakerNotes: "Welcome to the core of 2026 tech. We are moving from simple text predictors to autonomous agents that can plan, execute, and verify code."
  },
  {
    number: 2,
    title: "Evolution: Reasoning vs Pattern Matching",
    type: "Comparison",
    visualDescription: "Diagram comparing System 1 thinking (fast, intuitive) vs System 2 thinking (slow, logical).",
    bullets: ["2023: Next Token Prediction", "2025: Chain-of-Thought (CoT)", "Reasoning models spend more time 'thinking'", "Better planning, fewer hallucinations"],
    speakerNotes: "Early models were just fast pattern matchers. The new generation of 'Reasoning' models actually plan their steps before they output a single character, making them perfect for complex architecture."
  },
  {
    number: 3,
    title: "What is an AI Agent?",
    type: "Diagram",
    visualDescription: "An agent loop: Brain -> Planning -> Tool Use -> Environment -> Observation.",
    bullets: ["Autonomous goal-seeking behavior", "Access to external tools (Terminal, Web)", "Self-correction through feedback loops", "Memory: Short-term (Context) & Long-term"],
    speakerNotes: "An agent isn't just a chatbot. It's an LLM with 'hands'. It can run a command, see the error, and try a different approach without you typing a single word."
  },
  {
    number: 4,
    title: "The Agentic Coding Workflow",
    type: "Timeline",
    visualDescription: "Step-by-step flow: Requirement -> Agent Plans -> Code Gen -> Test Run -> Success.",
    bullets: ["1. Goal Definition", "2. Agent decomposes task", "3. Tool selection (Linter, Compiler)", "4. Execution & Verification", "5. Final Human-in-the-Loop Review"],
    speakerNotes: "This is how features are built now. You define the goal, the agent plans the steps, runs the tests, and only calls you for the final sanity check."
  },
  {
    number: 5,
    title: "Multi-Agent Systems",
    type: "Content",
    visualDescription: "A group of specialized agent icons: Architect, Coder, Reviewer, Tester.",
    bullets: ["Specialization beats generalists", "Swarm patterns for complex features", "Orchestration layers (LangGraph, CrewAI)", "Conflict resolution & Consensus"],
    speakerNotes: "In high-end environments, we use swarms. One agent architects, another codes, and a third purely focuses on finding bugs in the second agent's work."
  },
  {
    number: 6,
    title: "Exercise: Deploying an Agent",
    type: "Exercise",
    visualDescription: "Terminal interface showing 'Claude Code' or 'Devin' initializing a project.",
    bullets: ["Initialize a Terminal Agent", "Prompt: 'Setup a Vite project with Auth'", "Watch the agent handle dependencies", "Critique the agent's plan"],
    speakerNotes: "Let's actually use an agent. We'll give it a high-level task and watch it navigate the terminal, install packages, and handle the boilerplate automatically."
  },
  {
    number: 7,
    title: "Future of Agentic AI",
    type: "Recap",
    visualDescription: "A sunrise over a digital horizon.",
    bullets: ["Self-healing codebases", "Autonomous bug bounty hunters", "AI as a full-cycle teammate", "The human role: Intent & Ethics"],
    speakerNotes: "Agents will soon manage the 'maintenance' phase entirely. Our role is shifting to being the directors of these digital workforces."
  }
];

export const VIBE_CODING_SLIDES: Slide[] = [
  {
    number: 1,
    title: "Vibe Coding: The Course Outline",
    type: "Content",
    visualDescription: "An 8-module grid showing the progression from philosophy to mastery.",
    bullets: ["01. Defining the Vibe", "02. The AI-Native Mindset", "03. Tooling for 2026", "04. Frameworks (CRAFT)", "05. Iterative Workflows", "06. Advanced Patterns", "07. Risk Management", "08. Workshop Hands-On"],
    speakerNotes: "Welcome to the Vibe Coding masterclass. We're going to break down how to move from traditional manual coding to intent-based orchestration across these 8 core modules."
  },
  {
    number: 2,
    title: "What is Vibe Coding?",
    type: "Quote",
    visualDescription: "Large Karpathy quote on a clean, dark background with glowing text.",
    bullets: ["'You just describe it, AI writes it' - Karpathy", "Natural Language as the primary syntax", "High-level intent over low-level implementation", "The rise of the 'Software Conductor'"],
    speakerNotes: "Andrej Karpathy famously coined the term. It's the transition where our primary tool isn't the keyboard, but our ability to describe systems accurately in natural language."
  },
  {
    number: 3,
    title: "Traditional vs Vibe Coding",
    type: "Comparison",
    visualDescription: "A high-contrast comparison table highlighting efficiency and role shifts.",
    bullets: ["Trad: Syntax-heavy | Vibe: Intent-heavy", "Trad: Manual Boilerplate | Vibe: Instant Gen", "Trad: Slow Iteration | Vibe: Real-time Evolution", "Trad: Fixer | Vibe: Architect/Reviewer"],
    speakerNotes: "The shift is fundamental. In traditional coding, you are the bricklayer. In vibe coding, you are the architect and the quality inspector combined."
  },
  {
    number: 4,
    title: "The 6 Core Principles",
    type: "Diagram",
    visualDescription: "A 6-card grid with vibrant icons for each principle.",
    bullets: ["1. Conversation is Code", "2. Think in Systems, Not Lines", "3. Context is Your Most Valuable Asset", "4. Be an Editor, Not Just a Writer", "5. Fail Fast, Iterate Faster", "6. Validate with Rigor"],
    speakerNotes: "These six principles define success. You must treat your conversation with the AI as the source of truth, focus on systems architecture, and never trust output without validation."
  },
  {
    number: 5,
    title: "Essential Tools & Setup",
    type: "Content",
    visualDescription: "Logo showcase for Claude Code, Cursor, and Bolt.new.",
    bullets: ["Claude Code: The Terminal Agent", "Cursor: The AI-Native IDE", "Bolt.new: Full-stack in-browser", "v0.dev: UI/UX generation powerhouse"],
    speakerNotes: "2026 is about using the right tool for the right vibe. We use Cursor for deep engineering and Claude Code for rapid agentic task execution in the terminal."
  },
  {
    number: 6,
    title: "The CRAFT Framework",
    type: "Diagram",
    visualDescription: "Acronym breakdown: Context, Role, Action, Format, Test.",
    bullets: ["CONTEXT: Background & Constraints", "ROLE: Who should the AI be?", "ACTION: What is the specific task?", "FORMAT: Output style (JSON, React, etc.)", "TEST: How to verify success"],
    speakerNotes: "Use CRAFT to ensure your prompts never fail. By defining the Context and the Role before the Action, you get significantly higher quality code from the first prompt."
  },
  {
    number: 7,
    title: "Prompting: Weak vs Strong",
    type: "Comparison",
    visualDescription: "Side-by-side code/text blocks showing 'Build a button' vs a 'CRAFTed' prompt.",
    bullets: ["WEAK: 'Make a login page'", "STRONG: 'Act as a Senior React Dev...'", "Add constraints: Tailwind, Lucide, mobile-first", "Result: Clean code vs messy boilerplate"],
    speakerNotes: "Look at the difference. Specificity leads to maintainability. A strong prompt includes the tech stack, component structure, and error handling expectations upfront."
  },
  {
    number: 8,
    title: "The 5-Step Workflow",
    type: "Timeline",
    visualDescription: "Horizontal flow: Describe -> Generate -> Review -> Refine -> Integrate.",
    bullets: ["1. DESCRIBE: Define the intent clearly", "2. GENERATE: Let AI build the foundation", "3. REVIEW: Inspect logic & quality", "4. REFINE: Iterative prompt for polish", "5. INTEGRATE: Human-led PR merge"],
    speakerNotes: "This is the professional loop. You don't just take the first output. You review it, find the flaws, and use the AI to refine it until it meets production standards."
  },
  {
    number: 9,
    title: "Advanced Prompt Patterns",
    type: "Content",
    visualDescription: "Grid showing icons for Chain, Persona, Constraint, and Example-driven patterns.",
    bullets: ["Chain of Thought: Step-by-step logic", "Persona: Impersonate specific experts", "Constraints: Negative prompting (No divs!)", "Few-Shot: Give examples of your style"],
    speakerNotes: "To truly master the vibe, you need patterns. 'Chain of Thought' forces the AI to plan before it types a single line of code, reducing logical errors by 40%."
  },
  {
    number: 10,
    title: "Pitfalls & Best Practices",
    type: "Comparison",
    visualDescription: "Split layout with red 'Don'ts' and green 'Do's'.",
    bullets: ["DON'T: Blindly copy-paste", "DON'T: Give massive wall of text prompts", "DO: Keep logic modular and small", "DO: Use AI for testing as much as coding"],
    speakerNotes: "Avoid the trap of 'blind acceptance'. The biggest pitfall is letting the AI create a 'black box' that you don't understand. Keep your modules small and your reviews thorough."
  },
  {
    number: 11,
    title: "When to Vibe Code?",
    type: "Comparison",
    visualDescription: "Two columns: Great For vs Use With Caution.",
    bullets: ["GREAT: Rapid MVPs & Prototyping", "GREAT: CRUD & Boilerplate features", "CAUTION: Core security/auth logic", "CAUTION: Legacy monolith refactors"],
    speakerNotes: "Context matters. Vibe coding is incredible for speed, but for mission-critical security logic, you must manually drive every line with extreme Vibe Engineering precision."
  },
  {
    number: 12,
    title: "Real-World Impact",
    type: "Comparison",
    visualDescription: "Stats dashboard showing productivity gains and team speed increases.",
    bullets: ["50-80% reduction in boilerplate time", "3x faster feature velocity", "Smaller, more focused dev teams", "Shift toward 'Full-Cycle' developers"],
    speakerNotes: "The impact is undeniable. Teams adopting vibe coding are shipping features three times faster. It's not about working harder; it's about shifting where your effort goes."
  },
  {
    number: 13,
    title: "Hands-On Workshop",
    type: "Exercise",
    visualDescription: "Four cards with exercise prompts and time estimates.",
    bullets: ["Ex 1: Zero-to-One Prototype (15m)", "Ex 2: Refactor Legacy Mess (10m)", "Ex 3: The Testing Suite Agent (10m)", "Ex 4: UI Design to Code (15m)"],
    speakerNotes: "Laptops open. We're going to build a functional app from a sketch, then we'll use an agent to refactor a messy function into clean, documented Vibe Engineering."
  },
  {
    number: 14,
    title: "Key Takeaways",
    type: "Recap",
    visualDescription: "6 summary points in a circular layout.",
    bullets: ["1. Intent is the new syntax", "2. Master the CRAFT framework", "3. Review is more important than writing", "4. Tools are your force multipliers", "5. Context preservation is key", "6. Stay curious, stay skeptical"],
    speakerNotes: "Summary: Become the conductor. Master the intent, preserve the context, and always remain the final quality authority."
  },
  {
    number: 15,
    title: "THE FUTURE IS INTENT.",
    type: "Title",
    visualDescription: "Large, neon 'START VIBING' text over a futuristic city grid.",
    bullets: ["Workshop Ends. Mastery Begins.", "Join the AI-Native Revolution", "Build the Future, One Vibe at a Time.", "START VIBING."],
    speakerNotes: "That's it for the Vibe Coding session. The keyboard is no longer your limit. Your imagination and ability to describe systems are. Go out there and start vibing!"
  }
];

export const DOCUMENTING_WITH_AI_SLIDES: Slide[] = [
  {
    number: 1,
    title: "Documenting with AI",
    type: "Title",
    visualDescription: "Illustration of a robotic arm writing elegant calligraphy into a digital notebook.",
    bullets: ["Writing Less, Communicating More", "AI-Native Documentation", "Automating Technical Writing", "Precision & Clarity in 2026"],
    speakerNotes: "Documentation is often the most neglected part of software development. AI changes that by making high-quality documentation almost effortless to generate and maintain."
  },
  {
    number: 2,
    title: "From Requirements to PRDs",
    type: "Diagram",
    visualDescription: "Flow: Raw Meeting Notes -> AI Agent -> Structured PRD -> User Stories.",
    bullets: ["Drafting Product Requirement Docs", "Generating exhaustive User Stories", "Identifying missed edge cases", "Translating business needs to tech specs"],
    speakerNotes: "AI can take your messy meeting notes and transform them into a formal Product Requirements Document (PRD) in seconds. It can even suggest edge cases you might have missed."
  },
  {
    number: 3,
    title: "In-Code Documentation",
    type: "Demo",
    visualDescription: "Code block showing JSDoc and README generation using AI in real-time.",
    bullets: ["Automated JSDoc & Docstrings", "README.md generation from logic", "Explaining complex legacy code", "Consistency across the codebase"],
    speakerNotes: "Tools like GitHub Copilot and Cursor can document functions as you write them. No more 'I'll add comments later'—the AI does it instantly and accurately."
  },
  {
    number: 4,
    title: "API & System Architecture Docs",
    type: "Content",
    visualDescription: "Icons for Swagger, OpenAPI, and Mermaid.js diagrams.",
    bullets: ["OpenAPI/Swagger spec generation", "Mermaid diagram code from logic", "Internal API wikis via LLMs", "Self-healing documentation"],
    speakerNotes: "By pointing an AI at your routes, it can generate full OpenAPI specifications. It can even draw Mermaid.js diagrams that visualize your system architecture directly from the source code."
  },
  {
    number: 5,
    title: "The Agentic Review Loop",
    type: "Diagram",
    visualDescription: "Loop: Code Change -> Agent Syncs Docs -> Human Approves -> Published.",
    bullets: ["Documentation that never rots", "Agents monitoring code changes", "Auto-updating implementation guides", "Reduced onboarding time"],
    speakerNotes: "The biggest problem with docs is that they 'rot' or go out of sync. Agents in 2026 monitor your PRs and automatically suggest documentation updates to match the new reality."
  },
  {
    number: 6,
    title: "Exercise: Auto-Document This",
    type: "Exercise",
    visualDescription: "Large block of undocumented code on one side, empty README template on the other.",
    bullets: ["Paste a complex logic block", "Ask AI to generate a README", "Request a sequence diagram", "Review for technical accuracy"],
    speakerNotes: "Let's put this into practice. Take a complex function you've written and ask your AI tool to generate a full README section for it, including a usage example and a logic explanation."
  }
];

export const DESIGN_TO_APP_SLIDES: Slide[] = [
  {
    number: 1,
    title: "Turn Design into Application",
    type: "Title",
    visualDescription: "Split screen: A high-fidelity Figma design on the left transforming into clean React code on the right.",
    bullets: ["Bridge the Gap", "From Pixels to Production", "AI-Native UI Generation", "The v0, Lovable, & Bolt Workflow"],
    speakerNotes: "One of the most powerful uses of AI today is the ability to turn high-fidelity designs or even simple sketches into fully functional application scaffolding."
  },
  {
    number: 2,
    title: "The Vision-to-Code Pipeline",
    type: "Diagram",
    visualDescription: "Flowchart: Figma/Image -> AI Vision Model -> Component Structure -> Functional App.",
    bullets: ["Input: Screenshot or Figma URL", "AI interprets layout & styling", "Generation of responsive components", "Manual refinement & logic binding"],
    speakerNotes: "We're moving away from 'hand-coding' CSS for 4 hours. Now, we use vision models to understand the 'vibe' and layout, then generate the base code in seconds."
  },
  {
    number: 3,
    title: "Tool Spotlight: v0.dev",
    type: "Demo",
    visualDescription: "Screenshot of v0 interface generating a complex dashboard from a text prompt and image.",
    bullets: ["Vercel's AI UI generator", "Copy-pasteable Shadcn/UI code", "Iterative refinement via chat", "Built-in accessibility & responsiveness"],
    speakerNotes: "v0 is a game changer for React developers. It understands modern design systems and gives you code that is production-ready, not just a mess of divs."
  },
  {
    number: 4,
    title: "Tool Spotlight: Bolt.new",
    type: "Demo",
    visualDescription: "Bolt.new interface showing a full-stack app being built in the browser.",
    bullets: ["Full-stack generation", "In-browser runtime (WebContainers)", "Auto-installs dependencies", "One-click deployment"],
    speakerNotes: "Bolt goes a step further by not just giving you the UI, but setting up the entire project environment, including the backend logic and deployment scripts."
  },
  {
    number: 5,
    title: "The Iterative Refinement Loop",
    type: "Content",
    visualDescription: "Infinite loop icon: Generate -> Review -> Prompt -> Polish.",
    bullets: ["AI gives the 80% foundation", "Human handles the 20% complexity", "Refining animations & transitions", "Connecting real data sources"],
    speakerNotes: "The AI gets us 80% of the way there in seconds. Our job as engineers is the final 20%: the edge cases, the complex state logic, and the polish."
  },
  {
    number: 6,
    title: "Exercise: Sketch to UI",
    type: "Exercise",
    visualDescription: "Hand-drawn sketch of a profile page next to a generated React component.",
    bullets: ["Draw a simple UI on paper", "Upload to a Vision AI (Claude/GPT)", "Ask for a Tailwind component", "Refine the results in Cursor"],
    speakerNotes: "Let's try it. Sketch a simple login page or a profile card. We'll use AI to turn that doodle into a working React component."
  }
];

export const CONVENTIONAL_SDLC_SLIDES: Slide[] = [
  {
    number: 1,
    title: "COURSE AGENDA",
    type: "Content",
    visualDescription: "Vertical list of course modules with icons and short descriptions.",
    bullets: ["01. What is SDLC? (Definition & Purpose)", "02. SDLC Phases (7 key steps)", "03. SDLC Models (Methodologies)", "04. Roles & Responsibilities (Stakeholders)", "05. Tools & Best Practices (Industry Tips)", "06. Case Study & Summary"],
    speakerNotes: "Welcome to the SDLC training. We'll start with the fundamentals of what SDLC is, then deep dive into the 7 phases, various models, team roles, and conclude with professional best practices."
  },
  {
    number: 2,
    title: "WHAT IS SDLC?",
    type: "Diagram",
    visualDescription: "Three pillars showing Structure, Quality, and Efficiency under a master definition.",
    bullets: ["STRUCTURE: Roadmap for development", "QUALITY: Systematic checks & reduced defects", "EFFICIENCY: Optimized resource usage", "Systematic framework for creating software"],
    speakerNotes: "SDLC is a structured process that defines the tasks performed at each step. It ensures we don't just 'code' but 'engineer' with quality and efficiency in mind."
  },
  {
    number: 3,
    title: "WHY SDLC MATTERS",
    type: "Comparison",
    visualDescription: "Large statistic counters showing 70% failure risk vs 3x faster delivery benefits.",
    bullets: ["70% projects fail without methodology", "3x faster delivery with defined processes", "40% cost reduction via early detection", "Improved risk management & reliability"],
    speakerNotes: "Why do we use it? Because 70% of projects fail without it. A proper methodology triples your speed and cuts costs by nearly half through early defect detection."
  },
  {
    number: 4,
    title: "THE 7 PHASES OF SDLC",
    type: "Timeline",
    visualDescription: "A horizontal flow showing 7 numbered phases from Planning to Maintenance.",
    bullets: ["1. Planning | 2. Analysis | 3. Design", "4. Coding | 5. Testing", "6. Deployment | 7. Maintenance", "Each phase builds upon the previous one"],
    speakerNotes: "Software follows a lifecycle. We start with planning and analysis, move to design and coding, and finally test, deploy, and maintain. Execution of each phase is critical."
  },
  {
    number: 5,
    title: "PHASE 1: PLANNING",
    type: "Content",
    visualDescription: "Split view: Key Activities on left, Key Deliverables on right, Pro Tip box.",
    bullets: ["Activity: Define scope and objectives", "Deliverable: Project Charter & Schedule", "Deliverable: Resource Allocation Plan", "Pro Tip: Planning should be 20-30% of effort"],
    speakerNotes: "Planning establishes the foundation. You must define your scope and identify stakeholders early. Remember the pro tip: invest 20-30% of your total effort right here."
  },
  {
    number: 6,
    title: "PHASE 2: REQUIREMENTS ANALYSIS",
    type: "Diagram",
    visualDescription: "Four cards: Functional, Non-Functional, Techniques, and the SRS Document.",
    bullets: ["Functional: Features and user interactions", "Non-Functional: Speed, security, reliability", "Techniques: Interviews, workshops, surveys", "Output: SRS (Requirements Specification)"],
    speakerNotes: "Requirements tell us WHAT the system should do. We separate them into features (Functional) and performance characteristics (Non-Functional), documented in the SRS."
  },
  {
    number: 7,
    title: "PHASE 3: SYSTEM DESIGN",
    type: "Comparison",
    visualDescription: "Side-by-side comparison of High-Level Design (HLD) and Low-Level Design (LLD).",
    bullets: ["HLD: Architecture & Tech Stack selection", "HLD: DB Design (ER) & API Design", "LLD: Detailed class & activity diagrams", "LLD: Algorithms & Error handling strategies"],
    speakerNotes: "Design is where we build the blueprint. High-level design covers architecture and the tech stack, while low-level design gets into the actual class logic and algorithms."
  },
  {
    number: 8,
    title: "PHASE 4: IMPLEMENTATION / CODING",
    type: "Content",
    visualDescription: "Three columns: Coding Standards, Version Control, Integration & Build.",
    bullets: ["Standards: Clean code & naming conventions", "VC: Git management & reviews", "Build: CI/CD & unit test execution", "Translation of design into actual code"],
    speakerNotes: "This is the 'construction' phase. We focus on clean code standards, effective version control using Git, and automated integration through CI/CD pipelines."
  },
  {
    number: 9,
    title: "PHASE 5: TESTING & QA",
    type: "Diagram",
    visualDescription: "Testing pyramid showing levels of verification and other testing types list.",
    bullets: ["Pyramid: Unit -> Integration -> System -> UAT", "Unit: Test individual functions", "System: Test complete end-to-end", "Other: Performance, Security, Usability"],
    speakerNotes: "Testing is systematic verification. We follow the testing pyramid to ensure functionality at every layer, while also performing specialized checks like security and performance testing."
  },
  {
    number: 10,
    title: "PHASES 6 & 7: DEPLOY & MAINTAIN",
    type: "Comparison",
    visualDescription: "Split view between Deployment activities and Maintenance types.",
    bullets: ["Deployment: Big Bang, Rolling, Canary", "Setup: Staging vs Production environments", "Maintenance: Corrective & Adaptive", "Maintenance: Perfective & Preventive"],
    speakerNotes: "Going live involves strategic deployment and user training. Maintenance follows, covering bug fixes (Corrective) and environment updates (Adaptive) or refactoring (Preventive)."
  },
  {
    number: 11,
    title: "SDLC MODELS",
    type: "Diagram",
    visualDescription: "Six colored cards for Waterfall, Agile, V-Model, Spiral, Iterative, and DevOps.",
    bullets: ["Waterfall: Best for fixed scope projects", "Agile: Iterative sprints & feedback", "Spiral: Risk-driven for large projects", "DevOps: Continuous delivery focus"],
    speakerNotes: "Different projects need different methodologies. Waterfall is sequential; Agile is iterative; Spiral is risk-focused; DevOps is about speed and operations integration."
  },
  {
    number: 13,
    title: "ROLES & RESPONSIBILITIES",
    type: "Content",
    visualDescription: "Grid of 6 roles with descriptions of their core duties in the SDLC.",
    bullets: ["PM: Plans and tracks progress", "BA: Bridge between stake & tech", "Architect: Design & scalability", "Developer: Construction & maintenance", "QA: Defect tracking & test design", "PO: Prioritize based on business value"],
    speakerNotes: "Every team member has a vital role. The PM manages the timeline, while the Architect handles the blueprint and the PO ensures we build what the business actually needs."
  },
  {
    number: 14,
    title: "TOOLS & BEST PRACTICES",
    type: "Comparison",
    visualDescription: "Left side: Tool categories & examples. Right side: Best practices checklist.",
    bullets: ["Tools: PM, VC, CI/CD, Testing, Docs", "Best: Define clear requirements first", "Best: Implement automated testing early", "Best: Manage technical debt proactively"],
    speakerNotes: "Final takeaway: Tools like Jira and Git are essential, but best practices like early requirement definition and proactive technical debt management are what actually ensure success."
  }
];

export const WORKSHOP_CONTENT: WorkshopData = {
  title: "Software Development Using AI: A Hands-On Workshop",
  subtitle: "Adapt, Evolve, Build — Mastering AI-Driven Development in 2026",
  trainer: "Philips",
  duration: "4 Hours (Half-Day)",
  audience: "Software Developers & Engineers (Intermediate)",
  goal: "Master AI-driven workflows and transition from Vibe Coding to Vibe Engineering.",
  agenda: [
    { time: "09:00", session: "Opening & Ice Breaker", duration: "15 min", format: "Interactive", description: "Introduction, polls, and myth-busting about AI taking jobs." },
    { time: "09:15", session: "Session 1: Perkembangan AI 2023–2026", duration: "40 min", format: "Lecture + Discussion", description: "Timeline of the AI revolution from ChatGPT to Agentic Era." },
    { time: "09:55", session: "Session 2: Dampak AI pada Software Dev", duration: "40 min", format: "Lecture + Discussion", description: "What tasks are disappearing and how to survive as a T-shaped AI dev." },
    { time: "10:35", session: "☕ Coffee Break", duration: "15 min", format: "Break", description: "Networking and refreshments." },
    { time: "10:50", session: "Session 3: Pengembangan Konvensional", duration: "20 min", format: "Lecture + Reflection", description: "Reviewing the 'before' state of manual boilerplate and pain points." },
    { time: "11:10", session: "Session 4: Pengembangan Menggunakan AI", duration: "50 min", format: "Demo + Hands-On", description: "AI Thinking Framework, Vibe Coding, and Tool selection." },
    { time: "12:00", session: "Session 5: SDLC Workflow Using AI", duration: "45 min", format: "Demo + Hands-On", description: "Integrating AI into every phase from requirements to maintenance." },
    { time: "12:45", session: "Wrap-Up & Q&A", duration: "15 min", format: "Discussion", description: "Key takeaways and next steps for your AI starter kit." }
  ],
  slides: [
    {
      number: 1,
      title: "Software Development Using AI",
      type: "Title",
      visualDescription: "Dark tech background with glowing neural network nodes and electric teal title text.",
      bullets: ["Mastering AI-Driven Development in 2026", "Trainer: Philips", "Adapt, Evolve, Build"],
      speakerNotes: "Welcome everyone! My name is Philips, and today we move beyond simple chatbots and into true AI-native engineering. We aren't just learning tools; we're evolving our roles."
    },
    {
      number: 2,
      title: "Workshop Agenda",
      type: "Content",
      visualDescription: "Interactive timeline showing 5 sessions with duration icons.",
      bullets: ["Session 1: Evolution 2023-2026", "Session 2: Impact & Survival", "Session 3: Conventional Baseline", "Session 4: AI Development Mastery", "Session 5: AI-Enhanced SDLC"],
      speakerNotes: "We have a packed 4 hours. We'll start with context, move to skills, and finish with a full workflow you can use tomorrow."
    },
    {
        number: 3,
        title: "Quick Poll: Current Usage",
        type: "Exercise",
        visualDescription: "Large QR code for real-time polling or ✋ icon for show of hands.",
        bullets: ["Siapa yang sudah pakai AI?", "Paling sering pakai tool apa?", "Raise your hand if it's daily", "Daily usage vs Occasionally?"],
        speakerNotes: "Let's see where we stand. Raise your hands if you use AI daily. 💡 Ask: Which tool is your primary 'co-pilot' right now?"
    },
    {
        number: 4,
        title: "Ice Breaker: The 5-Year Vision",
        type: "Quote",
        visualDescription: "Large text: 'Will AI replace developers by 2031?' in a bold glitch-effect font.",
        bullets: ["No right answer", "Open discussion", "Perspective check", "The 2026 Reality"],
        speakerNotes: "This is the question on everyone's mind. Let's talk about it. What does a developer look like in 5 years? Transition: Let's see how we got here."
    },
    {
        number: 5,
        title: "Ground Rules",
        type: "Content",
        visualDescription: "Clean layout with icons for Wi-Fi, Coffee, and Interaction.",
        bullets: ["Ask questions anytime", "Hands-on participation required", "Phones on silent (mostly)", "Feel free to ask anytime"],
        speakerNotes: "This is a workshop, not a lecture. The more you experiment, the more you learn. Logistics: Wi-Fi is on the whiteboard."
    },
    {
      number: 6,
      title: "Session 1: Perkembangan AI 2023-2026",
      type: "Section Divider",
      visualDescription: "Dramatic '2023 -> 2026' timeline graphic with high-contrast colors.",
      bullets: ["From Chatbots to Agents", "The Era of Vibe Engineering", "Evolution as a journey"],
      speakerNotes: "Let's dive into the history. It's only been a few years, but it feels like a decade of innovation has happened."
    },
    {
        number: 7,
        title: "2023: The Breakout Year",
        type: "Timeline",
        visualDescription: "Timeline segment marked 2023. Logo collage: OpenAI, GitHub Copilot, LLaMA.",
        bullets: ["ChatGPT reaches 100M users", "Copilot adoption surges", "GPT-4 launches (Multimodal)", "Open source LLM explosion"],
        speakerNotes: "2023 was the wake-up call. We moved from 'AI is a toy' to 'AI can code crudely'. GPT-4 was the game changer for reasoning."
    },
    {
        number: 8,
        title: "2024: The Integration Year",
        type: "Timeline",
        visualDescription: "Timeline segment 2024. Screenshot: Cursor IDE side-by-side with VS Code.",
        bullets: ["AI embedded in IDEs", "Rise of Claude, Gemini, GPT-4o", "Cursor IDE gains traction", "Agents and multi-step workflows"],
        speakerNotes: "In 2024, AI moved inside the tools. Cursor showed us what an AI-native IDE looks like. We stopped copying and pasting into browser tabs."
    },
    {
        number: 9,
        title: "2025: The Agent Era",
        type: "Timeline",
        visualDescription: "Timeline segment 2025. Icons: Claude Code, Devin, Copilot Workspace.",
        bullets: ["Autonomous coding agents emerge", "Handling full features autonomously", "Shift from AI-assisted to AI-driven", "Open-source closes the gap"],
        speakerNotes: "Last year was about agents. Tools that don't just suggest lines, but complete entire Jira tickets with oversight."
    },
    {
        number: 10,
        title: "2026: Where We Are Now",
        type: "Timeline",
        visualDescription: "Current year (2026) highlighted with neon glow.",
        bullets: ["AI as a standard toolkit", "Vibe Coding becomes mainstream", "AI-native SDLC standard", "The developer role is evolving"],
        speakerNotes: "Today, AI isn't an add-on; it's the core. We aren't 'writing code' as much as we are 'architecting intent'."
    },
    {
        number: 15,
        title: "Session 2: Dampak AI",
        type: "Section Divider",
        visualDescription: "Split screen: 'Disruptive' (Red) vs 'Survivor' (Green).",
        bullets: ["Jobs lost vs Roles transformed", "Surviving the automation wave", "The T-Shaped AI Developer"],
        speakerNotes: "Let's get real about the impact. Some things are going away, and we need to be honest about that."
    },
    {
        number: 16,
        title: "Part A: AI Disruptive",
        type: "Content",
        visualDescription: "List of roles with a 'fading' animation effect.",
        bullets: ["Junior boilerplate tasks: Gone", "Manual QA/Testing: Automated", "Basic documentation writing", "Simple bug fixing / Review"],
        speakerNotes: "The low-level work is being commoditized. If your primary skill is writing boilerplate, you're at risk. 💡 Ask: What's the most boring part of your job?"
    },
    {
        number: 17,
        title: "What AI CANNOT Replace",
        type: "Comparison",
        visualDescription: "Brain vs CPU icon with 'Human Edge' highlighted.",
        bullets: ["System design & Architecture", "Deep business context understanding", "Creative problem solving", "Human judgment on trade-offs"],
        speakerNotes: "AI doesn't care about your company's long-term strategy. It doesn't know why a specific stakeholder prefers one UX over another. That's your value."
    },
    {
        number: 21,
        title: "Part B: Survive in AI Era",
        type: "Recap",
        visualDescription: "Graphic of a developer with 'AI Multiplier' label.",
        bullets: ["Mindset shift: From Coding to Orchestrating", "The new developer skill stack", "Prompt engineering & Tool mastery", "Be an 'AI multiplier' (1=5)"],
        speakerNotes: "Survival isn't about resisting. It's about being the person who can lead a team of AI agents. You are the conductor of the orchestra."
    },
    {
        number: 27,
        title: "Session 3: Conventional SDLC",
        type: "Section Divider",
        visualDescription: "Nostalgic, sepia-toned 'Retro' code editor look.",
        bullets: ["The 'Before' Picture", "Manual labor in software", "Why we shouldn't go back"],
        speakerNotes: "Let's look at the old way. Why? So we appreciate the new way and identify which habits we need to break."
    },
    {
        number: 28,
        title: "Traditional SDLC Workflow",
        type: "Diagram",
        visualDescription: "Slow-moving turtle icon next to 'Traditional SDLC'.",
        bullets: ["Requirements: Manual documents", "Design: Hand-drawn diagrams", "Coding: Writing from scratch", "Testing: Manual test writing"],
        speakerNotes: "Remember the days of hunting for that one CSS fix on Stack Overflow for 2 hours? That's the turtle era."
    },
    {
        number: 30,
        title: "Pain Points Summary",
        type: "Recap",
        visualDescription: "List of 'Pain' icons with crossed-out text.",
        bullets: ["Time-consuming boilerplate code", "Slow onboarding to codebases", "Repetitive documentation tasks", "Debugging through trial and error"],
        speakerNotes: "Dari pain points ini, mana yang paling sering kalian alami? This is our baseline for comparison."
    },
    {
        number: 33,
        title: "4A: AI Thinking Framework",
        type: "Diagram",
        visualDescription: "Loop graphic: Prompt -> Generate -> Review -> Iterate.",
        bullets: ["Think in INSTRUCTIONS, not just code", "Context is King", "Break big problems into tiny ones", "Always Validate"],
        speakerNotes: "The first rule of AI dev: Garbage in, garbage out. You need to provide context like you're talking to a very smart, very fast junior dev."
    },
    {
        number: 38,
        title: "4B: Vibe Coding",
        type: "Demo",
        visualDescription: "Screenshot of a prompt: 'Build a dashboard for sales' -> Working app.",
        bullets: ["'Just describe it, AI writes it'", "Natural Language to Code", "Great for Prototyping & MVPs", "Risk: Technical Debt accumulation"],
        speakerNotes: "Vibe coding is the 'magic' part. It's fast, it's fun, but it's dangerous for production. Let's see it in action. [Trainer: Show quick prompt demo]"
    },
    {
        number: 42,
        title: "4C: Vibe Coding vs Vibe Engineering",
        type: "Comparison",
        visualDescription: "Vibe Coding (Messy) vs Vibe Engineering (Clean Architecture).",
        bullets: ["Vibe Coding: 'Just make it work'", "Vibe Engineering: 'Make it work RIGHT'", "Architect + Reviewer role", "The Professional Path"],
        speakerNotes: "Professionals do vibe engineering. We don't just accept what the AI says. We tell the AI the architecture we want first."
    },
    {
        number: 46,
        title: "4D: AI Tools for Development",
        type: "Content",
        visualDescription: "Logo grid: Cursor, GitHub Copilot, Claude, v0, Bolt.",
        bullets: ["IDEs: Cursor, Windsurf, Copilot", "Chat: Claude, ChatGPT, Gemini", "UI: v0, Bolt.new, Lovable", "Start with 1-2, master them"],
        speakerNotes: "You don't need all of them. Pick one IDE and one chat model. Master them before expanding. 💡 Trainer Tip: Recommend Cursor + Claude 3.5 Sonnet."
    },
    {
        number: 49,
        title: "Session 5: AI SDLC Workflow",
        type: "Diagram",
        visualDescription: "Full circle SDLC with AI icons at every phase.",
        bullets: ["Phase 1: Req & Planning (AI PRD)", "Phase 2: Design & Arch (AI Diagram)", "Phase 3: Development (AI Agent)", "Phase 4: Testing & QA (AI Tests)"],
        speakerNotes: "Let's put it all together. How does AI fit into the whole lifecycle? Not just coding, but planning and deployment."
    },
    {
        number: 55,
        title: "Hands-on Exercise: AI SDLC",
        type: "Exercise",
        visualDescription: "Large 'HANDS ON' text with checklist.",
        bullets: ["Pilih satu fase SDLC", "Generate task (User story/Tests)", "Review and Iterate", "Document the results"],
        speakerNotes: "Your turn. Open your laptops. I want you to take a piece of code and let AI handle the 'boring' parts while you review."
    },
    {
        number: 60,
        title: "Wrap-Up: Key Takeaways",
        type: "Recap",
        visualDescription: "Top 5 list in bold, glowing text.",
        bullets: ["1. AI is evolving fast - Adapt!", "2. Vibe Engineering > Vibe Coding", "3. AI Thinking: Context is King", "4. AI supercharges every phase", "5. Human judgment is the edge"],
        speakerNotes: "If you remember nothing else, remember these five. You are the architect now."
    },
    {
        number: 64,
        title: "Thank You & Let's Build!",
        type: "Title",
        visualDescription: "Trainer contact info, QR code for feedback, and 'Let's Build' message.",
        bullets: ["Contact: Philips", "LinkedIn: [Your Profile]", "Next Steps: Your AI Kit"],
        speakerNotes: "Thank you for your time. Go out there and build something amazing with your new AI teammates! My name is Philips, feel free to connect."
    }
  ]
};
